spring.application.name=ai-bcp
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
spring.config.import=optional:file:.env[.properties]
spring.ai.model.chat=oci-genai

spring.ai.oci.genai.cohere.chat.options.model=${OCI_MODEL}
spring.ai.oci.genai.cohere.chat.options.compartment=${OCI_COMPARTMENT}
spring.ai.oci.genai.cohere.chat.options.servingMode=${OCI_SERVING_MODE}

spring.ai.oci.genai.authentication-type=file
spring.ai.oci.genai.file=${OCI_CONFIG_LOCATION}
spring.ai.oci.genai.profile=${OCI_CONFIG_PROFILE}
spring.ai.oci.genai.endpoint=${OCI_ENDPOINT}
spring.ai.oci.genai.region=${OCI_REGION}